image: Visual Studio 2019

install:
  - set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;C:\Miniconda3-x64\Library\bin;C:\Qt\5.15\mingw81_64\bin;%PATH%

build: off

after_test:
  - conda update -n base -c defaults conda --yes
  - conda create -n Pext python --yes
  - CALL conda.bat activate Pext
  - pip install -r requirements.txt
  - python setup.py || true
  - CALL conda.bat deactivate
  - ps: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
  - ps: wsl sudo apt-get update
  - ps: wsl sudo apt-get install jq --yes
  - ps: wsl bash prepare_activate_translations.sh 70 https://hosted.weblate.org/exports/stats/pext/?format=json
  - lrelease.exe pext/pext.pro
  - mkdir ..\Build
  - mkdir ..\Build\Pext
  - XCOPY /E /H /Y /C "*" ..\Build\Pext\
  - XCOPY /E /H /Y /C "C:\Miniconda3-x64\envs\Pext\*" ..\Build\
  - ps: echo "CD /d %~dp0" > ..\Build\Pext.bat1
  - ps: echo "START .\pythonw .\Pext\pext %*" >> ..\Build\Pext.bat1
  - ps: get-content ..\Build\Pext.bat1 | set-content ..\Build\Pext.bat
  - DEL ..\Build\Pext.bat1
  - cd ..\Build
  - echo !define APPNAME "Pext" > Pext.nsi
  - echo Name ${APPNAME} >> Pext.nsi
  - echo Icon 'Pext\pext\images\scalable\pext.ico' >> Pext.nsi
  - echo OutFile 'Pext.exe' >> Pext.nsi
  - echo RequestExecutionLevel admin >> Pext.nsi
  - echo InstallDir "$PROGRAMFILES\${APPNAME}" >> Pext.nsi
  - echo Page directory >> Pext.nsi
  - echo Page instfiles >> Pext.nsi
  - echo Section 'install' >> Pext.nsi
  - echo SetShellVarContext all >> Pext.nsi
  - echo SetOutPath $INSTDIR >> Pext.nsi
  - echo File /r '*' >> Pext.nsi
  - echo WriteUninstaller '$INSTDIR\uninstall.exe' >> Pext.nsi
  - echo CreateShortcut '$SMPROGRAMS\Pext.lnk' '$INSTDIR\Pext.bat' '' '$INSTDIR\Pext\pext\images\scalable\pext.ico' >> Pext.nsi
  - echo WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "DisplayName" "${APPNAME}" >> Pext.nsi
  - echo WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "UninstallString" "$\"$INSTDIR\uninstall.exe$\"" >> Pext.nsi
  - echo WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "QuietUninstallString" "$\"$INSTDIR\uninstall.exe$\" /S" >> Pext.nsi
  - echo WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "InstallLocation" "$\"$INSTDIR$\"" >> Pext.nsi
  - echo WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "DisplayIcon" "$\"$INSTDIR\Pext\pext\images\scalable\pext.ico$\"" >> Pext.nsi
  - echo WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "NoModify" 1 >> Pext.nsi
  - echo WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}" "NoRepair" 1 >> Pext.nsi
  - echo SectionEnd >> Pext.nsi
  - echo Section 'uninstall' >> Pext.nsi
  - echo SetShellVarContext all >> Pext.nsi
  - echo Delete "$SMPROGRAMS\Pext.lnk" >> Pext.nsi
  - echo RmDir /r "$INSTDIR" >> Pext.nsi
  - echo SectionEnd >> Pext.nsi
  - makensis Pext.nsi
  - cd ..\Pext
  - MOVE ..\Build\Pext.exe Pext.exe

artifacts:
  - path: Pext.exe

deploy:
  description: 'Continuous build'
  provider: GitHub
  auth_token:
    secure: AT7vsVoEUawTJp7iKtCx8RUxmMjZP1sBu72NCX+G2EHvdd3ubt0zCLBVINBpBFIw
  artifact: Pext.exe
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
    APPVEYOR_REPO_TAG_NAME: continuous
